#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p /var/lib/octavia/exabgp/run

mkfifo -m 0600 /var/lib/octavia/exabgp/run/exabgp.in
mkfifo -m 0600 /var/lib/octavia/exabgp/run/exabgp.out
